# Generated by Django 5.2.15 on 2026-07-06 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quizsession',
            name='default_marks',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='default_time_per_question_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Used when timer mode is "per question" and a question has no override.'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='marks_mode',
            field=models.CharField(choices=[('uniform', 'Same marks for every question'), ('per_question', 'Custom marks per question')], default='uniform', max_length=15),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='negative_marks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marks deducted for each wrong answer (enter as a positive number).', max_digits=6),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='timer_mode',
            field=models.CharField(choices=[('none', 'No timer'), ('per_quiz', 'One timer for the whole quiz'), ('per_question', 'Separate timer for each question')], default='per_quiz', max_length=15),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='total_time_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Used when timer mode is "whole quiz".'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - building questions'), ('active', 'Live - open to join & attempt'), ('ended', 'Ended')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='quizapp.category'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('guest_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('not_attempted_count', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quizapp.quizsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_marks', 'submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple choice'), ('true_false', 'True / False'), ('four_option', 'Four option')], default='mcq', max_length=15)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the session default (used only when marks mode is per-question).', max_digits=6, null=True)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='Leave blank to use the session default (used only when timer mode is per-question).', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizapp.quizsession')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='choice_images/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizapp.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizapp.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizapp.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizapp.choice')),
            ],
            options={
                'unique_together': {('participant', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='SessionParticipant',
        ),
    ]
