# Generated by Django 5.1.5 on 2026-08-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_category_quizsession_default_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='quiz_state',
            field=models.CharField(choices=[('waiting', 'Waiting to Start'), ('running', 'Running'), ('paused', 'Paused'), ('finished', 'Finished')], default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False')], default='mcq', max_length=15),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='total_time_minutes',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Used when timer mode is "whole quiz".', max_digits=5),
        ),
    ]
