# Generated by Django 5.1.5 on 2026-08-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_quizsession_quiz_state_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='current_question',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
