# Generated by Django 5.1.5 on 2026-08-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_quizsession_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
