# Generated by Django 5.1.5 on 2026-08-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_quizsession_question_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='quiz_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
